name: quietfox
favicon: null
layout_spectrum: 0.8409178031142801
typography_spectrum: 0.11610198323614895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5263486818876117
  lightness: 0.7823345959186554
  saturation: 0.7245003094431013
  rhythmicContrast: 0.7746577763464302
purpose: []
